# nursery/test-sprout.ps1
# Full end-to-end validator for the Strategy Garden sprout lifecycle.

param(
    [switch]$Kill
)

$strategyRoot = [System.IO.Path]::GetFullPath("$PSScriptRoot\..")
$seedPath = Join-Path $strategyRoot "entities\seeds\_testsprout.md"
$sproutDir = Join-Path $strategyRoot "entities\sprouts\testsprout"

Write-Host "--- PHASE 0: Cleaning Global State ---" -ForegroundColor Cyan
if (Test-Path $sproutDir) {
    Write-Host "Found existing testsprout. Unsprouting..." -ForegroundColor Gray
    if ($Kill) {
        pwsh nursery/unsprout.ps1 $sproutDir -Delete -Kill
    } else {
        pwsh nursery/unsprout.ps1 $sproutDir -Delete
    }
}

Write-Host "`n--- PHASE 1: Generating Test Seed ---" -ForegroundColor Cyan
if (Test-Path $seedPath) { Remove-Item $seedPath -Force }
$seedContent = @"
---
template_version: v37
title: testsprout
type: project
status: seed
description: "A dummy project used to test automated sprout pipelines."
AUTO-GENERATED FIELDS:
children: []
---
# Test Sprout
This is a dummy test generated by \`test-sprout.ps1\`.
"@
Set-Content -Path $seedPath -Value $seedContent -Encoding UTF8

Push-Location $strategyRoot
Write-Host "Rebuilding index to track seed..." -ForegroundColor Gray
pwsh gardener/build-index.ps1 | Out-Null

Write-Host "`n--- PHASE 2: Sprouting ---" -ForegroundColor Cyan
pwsh nursery/sprout.ps1 ./entities/seeds/_testsprout.md

$sproutDir = Join-Path $strategyRoot "entities\sprouts\testsprout"
if (-not (Test-Path $sproutDir)) {
    Write-Error "Sprouting failed. Directory $sproutDir not found."
    Pop-Location; exit 1
}

Write-Host "`n--- PHASE 3: Simulating App Setup in core/stable ---" -ForegroundColor Cyan
$coreStableDir = Join-Path $sproutDir "core\stable"

$serverContent = @"
const http = require('http');
let port = 3000;

// Scan specific argument for the dynamic {PORT} replacement mapped from build-pipeline
const portIndex = process.argv.indexOf('--port');
if (portIndex > -1) {
    port = parseInt(process.argv[portIndex + 1]);
}

const server = http.createServer((req, res) => {
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello from testsprout environment! Port: ' + port);
});

server.listen(port, () => {
    console.log('Test server actively running natively on port ' + port);
});
"@

$serverFile = Join-Path $coreStableDir "server.js"
Set-Content -Path $serverFile -Value $serverContent -Encoding UTF8

Write-Host "Committing dummy server into core/stable application branch..." -ForegroundColor Gray
Push-Location $coreStableDir
git add . | Out-Null
git commit -m "feat: built initial app server" | Out-Null
Pop-Location

Write-Host "`n--- PHASE 4: Automatically Running Pipeline Builder ---" -ForegroundColor Cyan
Push-Location $sproutDir
pwsh _nursery/scripts/build-pipeline.ps1 -RunCommand "node server.js --port {PORT}"
Pop-Location

Write-Host "`n--- TEST SPROUT COMPLETE! ---" -ForegroundColor Green
Write-Host "A clean NodeJS server is mapped across all four pipeline branches." -ForegroundColor Gray
Write-Host "To boot the 4 dynamic port servers, run:" -ForegroundColor Yellow
Write-Host "pwsh entities/sprouts/testsprout/_nursery/scripts/start-servers.ps1" -ForegroundColor Yellow

Pop-Location
