# tools/nursery/scripts/test-sprout.ps1
# Full end-to-end validator for the Strategy Garden sprout lifecycle.

param(
    [switch]$Kill
)

$strategyRoot = [System.IO.Path]::GetFullPath("$PSScriptRoot\..\..\..")
$seedPath = Join-Path $strategyRoot "entities\seeds\_testsprout.md"
$sproutDir = Join-Path $strategyRoot "entities\sprouts\testsprout"

Write-Host "--- PHASE 0: Cleaning Global State ---" -ForegroundColor Cyan

# Use the Nuclear Scavenger to ensure a clean state
$scavengeScript = Join-Path $strategyRoot "tools\nursery\scripts\scavenge.ps1"
if (Test-Path $scavengeScript) {
    pwsh $scavengeScript
}

if (Test-Path $sproutDir) {
    Write-Host "Found existing testsprout. Unsprouting..." -ForegroundColor Gray
    if ($Kill) {
        pwsh tools/nursery/scripts/unsprout.ps1 $sproutDir -Delete -Kill
    } else {
        pwsh tools/nursery/scripts/unsprout.ps1 $sproutDir -Delete
    }
}

Write-Host "`n--- PHASE 1: Generating Test Seed ---" -ForegroundColor Cyan
if (Test-Path $seedPath) { Remove-Item $seedPath -Force }
$seedContent = @"
---
template_version: v37
title: testsprout
type: project
status: seed
description: "A dummy project used to test automated sprout pipelines."
AUTO-GENERATED FIELDS:
children: []
---
# Test Sprout
This is a dummy test generated by \`test-sprout.ps1\`.
"@
Set-Content -Path $seedPath -Value $seedContent -Encoding UTF8

Push-Location $strategyRoot
Write-Host "Rebuilding index to track seed..." -ForegroundColor Gray
pwsh tools/gardener/scripts/build-index.ps1 | Out-Null

Write-Host "`n--- PHASE 2: Sprouting ---" -ForegroundColor Cyan
pwsh tools/nursery/scripts/sprout.ps1 ./entities/seeds/_testsprout.md

$sproutDir = Join-Path $strategyRoot "entities\sprouts\testsprout"
if (-not (Test-Path $sproutDir)) {
    Write-Error "Sprouting failed. Directory $sproutDir not found."
    Pop-Location; exit 1
}

Write-Host "`n--- PHASE 3: Simulating App Setup in pipeline/core/stable ---" -ForegroundColor Cyan
$coreStableDir = Join-Path $sproutDir "pipeline\core\stable"

# We drop the server into the STABLE worktree, as a developer would.
$serverContent = @'
const http = require('http');
const fs = require('fs');
const path = require('path');

let port = 3000;
const portIndex = process.argv.indexOf('--port');
if (portIndex > -1) { port = parseInt(process.argv[portIndex + 1]); }

const server = http.createServer((req, res) => {
    let nurseryVersion = "Unknown";
    let envVersion = "Unknown";
    try {
        let nursePath = path.join(__dirname, '.nurse/VERSION');
        if (!fs.existsSync(nursePath)) nursePath = path.join(__dirname, '../.nurse/VERSION');
        if (!fs.existsSync(nursePath)) nursePath = path.join(__dirname, '../../.nurse/VERSION');
        if (!fs.existsSync(nursePath)) nursePath = path.join(__dirname, '../../../.nurse/VERSION');
        if (fs.existsSync(nursePath)) nurseryVersion = fs.readFileSync(nursePath, 'utf8').trim();
        if (fs.existsSync(path.join(__dirname, 'VERSION'))) envVersion = fs.readFileSync(path.join(__dirname, 'VERSION'), 'utf8').trim();
    } catch (e) {}

    res.writeHead(200, {'Content-Type': 'text/html'});
    res.end(`<h1>Strategy Garden</h1><p>Running on Port: ${port}</p><p>Nursery: v${nurseryVersion}</p><p>App: v${envVersion}</p>`);
});

server.listen(port, () => { console.log('Server running on port ' + port); });
'@

$serverFile = Join-Path $coreStableDir "server.js"
Set-Content -Path $serverFile -Value $serverContent -Encoding UTF8

Write-Host "Committing dummy server into stable (no prefix nesting)..." -ForegroundColor Gray
Push-Location $coreStableDir
git add server.js | Out-Null
git commit -m "feat: built initial app server" | Out-Null
Pop-Location

Write-Host "`n--- PHASE 4: Automatically Running Pipeline Builder ---" -ForegroundColor Cyan
Push-Location $sproutDir
pwsh .nurse/dist/scripts/build-pipeline.ps1 -RunCommand "node server.js --port {PORT}"
Pop-Location

Write-Host "`n--- PHASE 5: Booting & Verifying Pipeline ---" -ForegroundColor Cyan
Push-Location $sproutDir
pwsh .nurse/dist/scripts/start-servers.ps1

# Wait for boot
Write-Host "Waiting for servers to initialize..." -ForegroundColor Gray
Start-Sleep -Seconds 5

$tier = Get-Content .nurse/.porttier -Raw
$envs = @(
    @{ Name = "stable"; Port = [int]"${tier}10" },
    @{ Name = "b-test"; Port = [int]"${tier}11" },
    @{ Name = "a-test"; Port = [int]"${tier}12" },
    @{ Name = "merge";  Port = [int]"${tier}13" }
)

$allValid = $true
foreach ($e in $envs) {
    if (-not (Test-Path "pipeline/core/$($e.Name)/server.js")) {
        Write-Error "CRITICAL: server.js missing in pipeline/core/$($e.Name)!"
        $allValid = $false
    }
    
    $conn = Get-NetTCPConnection -LocalPort $e.Port -ErrorAction SilentlyContinue
    if ($null -eq $conn) {
        Write-Error "CRITICAL: Stage $($e.Name) NOT listening on port $($e.Port)!"
        $allValid = $false
    } else {
        Write-Host "SUCCESS: Stage $($e.Name) active on port $($e.Port)." -ForegroundColor Green
    }
}

if ($allValid) {
    Write-Host "`n--- TEST SPROUT SUCCESSFUL! ---" -ForegroundColor Green
    Write-Host "All 4 environments are online and functional on port tier $tier." -ForegroundColor Gray
    
    # Restart the dashboard after successful test
    Write-Host "Restarting Pipeline Dashboard..." -ForegroundColor Cyan
    Start-Process pwsh -ArgumentList "-NonInteractive", "-Command", "cd '$strategyRoot'; pwsh tools/nursery/scripts/start-dashboard.ps1" -WindowStyle Hidden
} else {
    Write-Error "Test sprout failed validation."
    Pop-Location; exit 1
}

Pop-Location
Pop-Location
