# tools/nursery/scripts/test-sprout.ps1
# Full end-to-end validator for the Strategy Garden sprout lifecycle.

param(
    [switch]$Kill
)

$strategyRoot = [System.IO.Path]::GetFullPath("$PSScriptRoot\..\..\..")
$seedPath = Join-Path $strategyRoot "entities\seeds\_testsprout.md"
$sproutDir = Join-Path $strategyRoot "entities\sprouts\testsprout"

Write-Host "--- PHASE 0: Cleaning Global State ---" -ForegroundColor Cyan

# Use the Nuclear Scavenger to ensure a clean state
$scavengeScript = Join-Path $strategyRoot "tools\nursery\scripts\scavenge.ps1"
if (Test-Path $scavengeScript) {
    pwsh $scavengeScript
}

if (Test-Path $sproutDir) {
    Write-Host "Found existing testsprout. Unsprouting..." -ForegroundColor Gray
    if ($Kill) {
        pwsh tools/nursery/scripts/unsprout.ps1 $sproutDir -Delete -Kill
    } else {
        pwsh tools/nursery/scripts/unsprout.ps1 $sproutDir -Delete
    }
}

Write-Host "`n--- PHASE 1: Generating Test Seed ---" -ForegroundColor Cyan
if (Test-Path $seedPath) { Remove-Item $seedPath -Force }
$seedContent = @"
---
template_version: v37
title: testsprout
type: project
status: seed
description: "A dummy project used to test automated sprout pipelines."
AUTO-GENERATED FIELDS:
children: []
---
# Test Sprout
This is a dummy test generated by \`test-sprout.ps1\`.
"@
Set-Content -Path $seedPath -Value $seedContent -Encoding UTF8

Push-Location $strategyRoot
Write-Host "Rebuilding index to track seed..." -ForegroundColor Gray
pwsh tools/gardener/scripts/build-index.ps1 | Out-Null

Write-Host "`n--- PHASE 2: Sprouting ---" -ForegroundColor Cyan
pwsh tools/nursery/scripts/sprout.ps1 ./entities/seeds/_testsprout.md

$sproutDir = Join-Path $strategyRoot "entities\sprouts\testsprout"
if (-not (Test-Path $sproutDir)) {
    Write-Error "Sprouting failed. Directory $sproutDir not found."
    Pop-Location; exit 1
}

Write-Host "`n--- PHASE 3: Simulating App Setup in pipeline/core/stable ---" -ForegroundColor Cyan
$coreStableDir = Join-Path $sproutDir "pipeline\core\stable"

$serverContent = @'
const http = require('http');
const fs = require('fs');
const path = require('path');

let port = 3000;

// Scan specific argument for the dynamic {PORT} replacement
const portIndex = process.argv.indexOf('--port');
if (portIndex > -1) {
    port = parseInt(process.argv[portIndex + 1]);
}

const server = http.createServer((req, res) => {
    let nurseryVersion = "Unknown";
    let envVersion = "Unknown";

    try {
        nurseryVersion = fs.readFileSync(path.join(__dirname, '../../../.nurse/VERSION'), 'utf8').trim();
        envVersion = fs.readFileSync(path.join(__dirname, 'VERSION'), 'utf8').trim();
    } catch (e) {
        console.error("Version read failed:", e.message);
    }

    res.writeHead(200, {'Content-Type': 'text/html'});
    res.end(`
        <div style="font-family: sans-serif; padding: 2rem; background: #f4f4f9; border-radius: 8px; max-width: 450px; margin: 2rem auto; box-shadow: 0 4px 12px rgba(0,0,0,0.15); border: 1px solid #ddd;">
            <h1 style="color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 0.5rem; margin-top: 0;">Strategy Sprout</h1>
            <p style="font-size: 1.1rem; color: #7f8c8d;"><strong>Environment Port:</strong> ${port}</p>
            <div style="background: #fff; padding: 1.5rem; border-radius: 6px; border-left: 5px solid #2ecc71; margin-top: 1.5rem;">
                <div style="display: flex; justify-content: space-between; margin-bottom: 0.8rem;">
                    <span style="color: #34495e; font-weight: bold;">Blueprint Generation:</span>
                    <span style="background: #ecf0f1; padding: 2px 8px; border-radius: 4px; font-family: monospace;">v${nurseryVersion}</span>
                </div>
                <div style="display: flex; justify-content: space-between;">
                    <span style="color: #34495e; font-weight: bold;">Environment App:</span>
                    <span style="background: #e8f4fd; color: #2980b9; padding: 2px 8px; border-radius: 4px; font-family: monospace; font-weight: bold;">v${envVersion}</span>
                </div>
            </div>
            <p style="font-size: 0.8rem; color: #95a5a6; margin-top: 1.5rem; text-align: center;">Idempotent Garden Pipeline Active</p>
        </div>
    `);
});

server.listen(port, () => {
    console.log('Test server actively running natively on port ' + port);
});
'@

$serverFile = Join-Path $coreStableDir "server.js"
Set-Content -Path $serverFile -Value $serverContent -Encoding UTF8

Write-Host "Committing dummy server into core/stable application branch..." -ForegroundColor Gray
Push-Location $coreStableDir
git add . | Out-Null
git commit -m "feat: built initial app server" | Out-Null
Pop-Location

Write-Host "`n--- PHASE 4: Automatically Running Pipeline Builder ---" -ForegroundColor Cyan
Push-Location $sproutDir
pwsh .nurse/dist/scripts/build-pipeline.ps1 -RunCommand "node server.js --port {PORT}"
Pop-Location

Write-Host "`n--- TEST SPROUT COMPLETE! ---" -ForegroundColor Green
Write-Host "A clean NodeJS server is mapped across all four pipeline branches." -ForegroundColor Gray
Write-Host "To boot the 4 dynamic port servers, run:" -ForegroundColor Yellow
Write-Host "pwsh entities/sprouts/testsprout/.nurse/dist/scripts/start-servers.ps1" -ForegroundColor Yellow

Pop-Location
